# Generated by Django 5.0.1 on 2024-01-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(editable=False, max_length=200)),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField()),
                ('previous_hash', models.CharField(default='0', editable=False, max_length=50)),
            ],
        ),
    ]
